### ISSUE TITLE
ADD Antenna connectors selection in XVTR

### ISSUE THREAD

**Issue by IZ0JNY** [ExpertSDR3/ExpertSDR3-SUGGESTIONS#127]
Regarding the XVTR I would kindly ask to raise EE attention to a suggestion.

When you use a transverter (i own a SunSDR2 PRO and SunSDR2 DX) and you activate the corresponding bands from B.M. (Band1, Band2, Band3,etc.etc.) then for TX you only have the option DAC.out and for RX you only have the option ADC.in. 

This means that for using an external transverter you need 2 lines, 1 for TX and 1 for RX. 

In practice it means that you have to purchase an external coaxial relay to switch between TX and RX in order to use only 1 line. 90% of the transverter used in ham radio has 1 line (Kuhen for example: https://shop.kuhne-electronic.com/kuhne/en/shop/converter-transverte/transverter/  

Would it be possible to give the choice in ESDR to also use VHF and HF1 antenna connectors in XVTR mode ? If yes this could be a great improvement in my opinion. 

thanks.
Ivan - IZ0JNY

**Comment by ct1drb** [comment]
I agree with Ivan - IZ0JNY.

Best 73.

CT1DRB/OK8RB
David Quental

**Comment by LA9AKA** [comment]
I also agree!

**Comment by iw7dmh** [comment]
Yes please, I agree with Ivan

Best 73'
Enzo, iw7dmh

**Comment by IZ0JNY** [comment]
additional explanation. 

On the new transverters Kuhne for 3, 13 and 23cm they only have 1 line for TX/RX (https://tinyurl.com/kuhne10G5). I'm already using these Kuhne transverter on SunSDr using VHF single line putting VHF.1 for TX and VHF.1 for RX . Would be nice to have a window (already present, the XVTR window) where you can set the LO frequency and display on the main ESDR window the corresponding transverter frequency.

**Comment by ZL3RC** [comment]
While your approach has some merit Ivan I personally dont think its a good way to go.
What Im going to do is use the ADC/DAC ports, as thats what they are there for, as it leaves the A1,A2 and A3 ports free for other operations. My approach is to use three HF bands to drive three TRV's, thus 14Mhz to drive 144Mhz TRV (you need to do this to keep all the IF's below 55Mhz. If you look at the block digram 144Mhz is under sampled and therefore can not be used along with another RX/TX on 50Hmz and below) , 28Mhz to drive 432Mhz TRV and 50Mhz to drive 23cm TRV. These IF chooses avoid the need to have the out of band TX option but if need be could be moved to free up the 50Mhz with that option. These three TRV's would have filtered IF outputs and then combined into one line to ADC/DAC. The PTT would be controlled by two bits of the 7 outputs selectable on the B.M menu. With this approach you would get the option to listen to VHF/UHF while still retaining the three A ports to listen to HF and 6m (but you'd have to move the 23cm IF to do this). So you get the option of being able to have to VHF/UHF in either RX in ESDR3 and still monitor any HF band. 
Yes it requires some work but its not hard to do. Also remember that Kuhne TRV's can easily be modified to driven with much less that 5W, something like 20/30mw I think.
73
Roger ZL3RC

**Comment by oh4mvh** [comment]
My opinion is also to add all physical antenna connector selection possibilities (A1,A2 and A3) and per band for transverter configuration XVTR window. Then it gives most flexible solution for users who wants to use transverters.
The same transverter configuration XVTR window has configuration possibility for ext ctrl pins where user can control e.g. external relay board to select and drive different transverters e.g. connected to A2 physical connector. (Low power and e.g 10m doesn't require much of relay performance.)
If there is a concern for too high power coming out from the rig, then external ALC support is one way to go. Another option could be to add one more output power slider setting per transverter band on the transverter configuration XVTR window which overrides the global output power setting. Then it would make also possible for users like me who have several bands transverters to one and the same intermediate frequency 10m to use even directly 10m safely - eesdr3 software knows on which band I want to operate throught the band selection buttons.
Hopefully Expert Electronics can consider these proposals in coming upgrades. SunSDR2 Pro is a good choice of a rig for use together with transverter due to its safe output power settings mechanisms, rather low output power compared to many other rigs on the market and it has 10MHz ext ref build in. 
73 Petri oh4mvh

**Comment by KC4CBQ** [comment]
So Roman, why did this get closed without input from EE? I Too would like the option to select A2 or A3 with transverter function. From what I can see hardware will support this, so it is software that needs the option.

**Comment by ZL3RC** [comment]
If you watch the EE Update that was streamed 31/12/2022 Vasily makes a comment about this so I expect it to be available in  in a coming update. Soon I hope as it will make VHF/UHF and Microwave operation much easier.
https://www.youtube.com/watch?v=-WWBRrLc_D8

73 Roger ZL3RC

**Comment by IZ0JNY** [comment]
hello, I agree, availability of all Antenna connectors in Transverter mode will improve a lot microwaves and transverters activities. 

Roman told me this implementation will be done, I hope to find it on the next release. 

73 Ivan IZ0JNY

**Comment by rvolchkov** [comment]
Fix will be presented in the coming release
